server:
  port: 8081
  servlet:
    contextPath: /
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: itzi.enriquez@people-media.com.mx
    password: iisvuctckmysiumy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: ${mots_CONNECTION_DB}
    username: ${mots_USERNAME_DB}
    password: ${mots_PASSWORD_DB}

    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      maximum-pool-size: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  server:
    name: oauth

management:
  endpoints:
    web:
      exposure:
        include: "*"
