server:
  port: 8080
  servlet:
    contextPath: /msadt-auth
  tomcat: 
    uri-encoding: UTF-8
spring:
  mail:
     default-encoding: UTF-8
     host: relay.imss.gob.mx
     username: adt.imss@imss.gob.mx
     port: 25
     properties:
       mail:
        smtp:
         connectiontimeout:5000
         timeout:5000
  datasource:
      platform: mariadb
      driverClassName: org.mariadb.jdbc.Driver
      url: jdbc:mysql://10.250.9.41:3306/ADTCOREBDQA #${adt_CONNECTION_DB}
      username: ADTEDS_USER #${adt_USERNAME_DB}
      password: ADT3D5_US3R #${adt_PASSWORD_DB}

      timeBetweenEvictionRunsMillis: 1000
      testWhileIdle: true
      validationQuery: SELECT 1
      hikari:
        maximum-pool-size: 1
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  server:
    name: oauth

management:
  endpoints:
    web:
      exposure:
        include: "*"
      
ms.login.oauth.app.name: SAD
